[functions]
    directory = "./src/handlers"
    node_bundler = "esbuild"
    external_node_modules = ["sharp", "zod"]

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/to-webp/:splat"
    status = 200
    force = true
